### ISSUE TITLE
The input file path cannot be specified multiple times

### ISSUE THREAD

**Issue by olandese** [aliencube/bicep-build-actions#3]
I am running the action but I get the following error:

Run aliencube/bicep-build-actions@v0.1
  with:
    files: **/*.bicep
/usr/bin/docker run --name e449ea273a26c446f4b67a41e6a1a0489c_97cd55 --label 5588e4 --workdir /github/workspace --rm -e INPUT_FILES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/infra/infra":"/github/workspace" 5588e4:49ea273a26c446f4b67a41e6a1a0489c  "**/*.bicep"

this is my workflow step:

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: '**/*.bicep'

**Comment by justinyoo** [comment]
@olandese Thanks for the issue!

According to [this issue](https://github.com/Azure/bicep/issues/2170), from v0.3.1, building multiple .bicep files is no longer supported.

But let me find a way whether this Action can support it or not.

**Comment by justinyoo** [comment]
This Action now supports multiple files. Please give it a try with v0.3
